name: ðŸ› Bug Report
description: Report a bug with a reproducible test case
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! 
        
        **Important**: All bug reports must include a reproducible failing test case. This helps us understand the issue and ensures it gets fixed properly.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what you expected to happen vs. what actually happened
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: |
        **Required**: You must provide a failing test that reproduces the bug.
        
        Please fork the repository and add your failing test to `spec/failing.spec.ts`, then link to your fork or provide the test code here.
        
        Example structure:
        ```typescript
        it("should reproduce the bug - description", async () => {
          // Your test code that demonstrates the bug
          let input = [1, 2, 3];
          let result = await toArray(pipe(from(input), yourOperator()));
          expect(result).to.deep.equal([expected]); // This should fail
        });
        ```
      placeholder: |
        1. Add failing test to spec/failing.spec.ts
        2. Run `npm test` to confirm it fails
        3. Provide the test code here or link to your fork
        4. Describe the specific steps to reproduce
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include any error messages.
      placeholder: Describe what actually happened, include stack traces if applicable
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide information about your environment:
      value: |
        - OS: [e.g. Windows 11, macOS 14, Ubuntu 22.04]
        - Node.js version: [e.g. 18.17.0]
        - Package version: [e.g. 1.0.0-beta.1]
        - TypeScript version: [e.g. 5.1.6]
      render: markdown
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful

  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements Checklist
      description: Please confirm you've met these requirements
      options:
        - label: I have created a failing test that reproduces this bug
          required: true
        - label: I have verified the test fails with the current version
          required: true
        - label: I have checked existing issues to avoid duplicates
          required: true
        - label: I have provided clear steps to reproduce the issue
          required: true
