blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/MeirionHughes/web-streams-extensions/discussions
    about: For questions, ideas, and general discussions about the project
  - name: 📖 Documentation
    url: https://github.com/MeirionHughes/web-streams-extensions/blob/master/README.md
    about: Check the README and documentation first
