name: 📚 Documentation Issue
description: Report an issue with documentation
title: "[Docs]: "
labels: ["documentation"]
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: Documentation Issue
      description: What's wrong with the documentation?
      placeholder: Describe the documentation issue (missing, incorrect, unclear, etc.)
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Where is the documentation issue located?
      placeholder: e.g., README.md line 45, API docs for timeout operator, etc.
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: Describe your suggested changes or improvements

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the documentation issue
