import { toTransform } from "./to-transform.js";

import { buffer } from "./operators/buffer.js";
import { catchError } from "./operators/catchError.js";
import { concatAll } from "./operators/concatAll.js";
import { concatMap } from "./operators/concatMap.js";
import { count } from "./operators/count.js";
import { debounceTime } from "./operators/debounceTime.js";
import { defaultIfEmpty } from "./operators/defaultIfEmpty.js";
import { delay } from "./operators/delay.js";
import { distinct } from "./operators/distinct.js";
import { distinctUntilChanged } from "./operators/distinctUntilChanged.js";
import { distinctUntilKeyChanged } from "./operators/distinctUntilKeyChanged.js";
import { exhaustAll } from "./operators/exhaustAll.js";
import { exhaustMap } from "./operators/exhaustMap.js";
import { filter } from "./operators/filter.js";
import { first } from "./operators/first.js";
import { ignoreElements } from "./operators/ignoreElements.js";
import { last } from "./operators/last.js";
import { map } from "./operators/map.js";
import { mapSync } from "./operators/mapSync.js";
import { mergeAll } from "./operators/mergeAll.js";
import { mergeMap } from "./operators/mergeMap.js";
import { on } from "./operators/on.js";
import { onComplete } from "./operators/on-complete.js";
import { pairwise } from "./operators/pairwise.js";
import { reduce } from "./operators/reduce.js";
import { scan } from "./operators/scan.js";
import { schedule } from "./operators/schedule.js";
import { skip } from "./operators/skip.js";
import { skipWhile } from "./operators/skipWhile.js";
import { startWith } from "./operators/startWith.js";
import { switchAll } from "./operators/switchAll.js";
import { switchMap } from "./operators/switchMap.js";
import { take } from "./operators/take.js";
import { takeUntil } from "./operators/takeUntil.js";
import { takeWhile } from "./operators/takeWhile.js";
import { tap } from "./operators/tap.js";
import { throttleTime } from "./operators/throttleTime.js";
import { through } from "./operators/through.js";
import { timeout } from "./operators/timeout.js";
import { withLatestFrom } from "./operators/withLatestFrom.js";

export const BufferTransform = /* @__PURE__ */ toTransform(buffer);
export const CatchErrorTransform = /* @__PURE__ */ toTransform(catchError);
export const ConcatAllTransform = /* @__PURE__ */ toTransform(concatAll);
export const ConcatMapTransform = /* @__PURE__ */ toTransform(concatMap);
export const CountTransform = /* @__PURE__ */ toTransform(count);
export const DebounceTimeTransform = /* @__PURE__ */ toTransform(debounceTime);
export const DefaultIfEmptyTransform = /* @__PURE__ */ toTransform(defaultIfEmpty);
export const DelayTransform = /* @__PURE__ */ toTransform(delay);
export const DistinctTransform = /* @__PURE__ */ toTransform(distinct);
export const DistinctUntilChangedTransform = /* @__PURE__ */ toTransform(distinctUntilChanged);
export const DistinctUntilKeyChangedTransform = /* @__PURE__ */ toTransform(distinctUntilKeyChanged);
export const ExhaustAllTransform = /* @__PURE__ */ toTransform(exhaustAll);
export const ExhaustMapTransform = /* @__PURE__ */ toTransform(exhaustMap);
export const FilterTransform = /* @__PURE__ */ toTransform(filter);
export const FirstTransform = /* @__PURE__ */ toTransform(first);
export const IgnoreElementsTransform = /* @__PURE__ */ toTransform(ignoreElements);
export const LastTransform = /* @__PURE__ */ toTransform(last);
export const MapTransform = /* @__PURE__ */ toTransform(map);
export const MapSyncTransform = /* @__PURE__ */ toTransform(mapSync);
export const MergeAllTransform = /* @__PURE__ */ toTransform(mergeAll);
export const MergeMapTransform = /* @__PURE__ */ toTransform(mergeMap);
export const OnTransform = /* @__PURE__ */ toTransform(on);
export const OnCompleteTransform = /* @__PURE__ */ toTransform(onComplete);
export const PairwiseTransform = /* @__PURE__ */ toTransform(pairwise);
export const ReduceTransform = /* @__PURE__ */ toTransform(reduce);
export const ScanTransform = /* @__PURE__ */ toTransform(scan);
export const ScheduleTransform = /* @__PURE__ */ toTransform(schedule);
export const SkipTransform = /* @__PURE__ */ toTransform(skip);
export const SkipWhileTransform = /* @__PURE__ */ toTransform(skipWhile);
export const StartWithTransform = /* @__PURE__ */ toTransform(startWith);
export const SwitchAllTransform = /* @__PURE__ */ toTransform(switchAll);
export const SwitchMapTransform = /* @__PURE__ */ toTransform(switchMap);
export const TakeTransform = /* @__PURE__ */ toTransform(take);
export const TakeUntilTransform = /* @__PURE__ */ toTransform(takeUntil);
export const TakeWhileTransform = /* @__PURE__ */ toTransform(takeWhile);
export const TapTransform = /* @__PURE__ */ toTransform(tap);
export const ThrottleTimeTransform = /* @__PURE__ */ toTransform(throttleTime);
export const ThroughTransform = /* @__PURE__ */ toTransform(through);
export const TimeoutTransform = /* @__PURE__ */ toTransform(timeout);
export const WithLatestFromTransform = /* @__PURE__ */ toTransform(withLatestFrom);